show databases;
use `awesome chocolates`; 
 SELECT * FROM `awesome chocolates`.sales;
 -- What is the total revenue (Amount) generated by each salesperson?
 SELECT 
    p.Salesperson, SUM(Amount) AS total_revenue
FROM
    sales AS s
        JOIN
    people AS p USING (SPID)
GROUP BY p.Salesperson
ORDER BY total_revenue DESC;
-- Which product generated the highest revenue?
select sum(Amount) as "total_revenue",pr.Product
from sales as s
join products as pr
using(PID)
group by pr.Product
order by total_revenue DESC
limit 1;
-- Which team generated the highest total revenue?
 SELECT 
    p.Team, SUM(Amount) AS total_revenue
FROM
    sales AS s
        JOIN
    people AS p USING (SPID)
    where p.Team is not null and p.Team !=' '
GROUP BY p.Team
ORDER BY total_revenue DESC
limit 1;
-- Which region had the highest number of customers?
SELECT 
   g.Region, sum(s.Customers) as Highest_Customers
FROM
    `awesome chocolates`.geo AS g
        JOIN
    sales AS s USING (GeoID)
    where Region is not null and Region != ' '
    Group by g.Region
    order by Highest_Customers DESC
    limit 1;
    -- What’s the average number of boxes sold per sale?
    select avg(Boxes) as avg_num_of_boxes from sales ;
    -- Who is the top-performing salesperson based on revenue?
    SELECT 
   SUM(s.Amount) AS Total_revenue, p.Salesperson,
    RANK() OVER (ORDER BY SUM(s.Amount) DESC) AS Revenue_Rank
FROM
    sales AS s
        JOIN
    people AS p USING (SPID)
    where p.Salesperson is not null and p.Salesperson !=" "
GROUP BY p.Salesperson
ORDER BY Revenue_Rank  DESC;
-- What is the total revenue per region?
 SELECT 
    g.Region, SUM(s.Amount) AS total_revenue
FROM
    sales AS s
        JOIN
    geo AS g USING (GeoID)
    where g.Region is not null and g.Region != ' '
GROUP BY g.Region
ORDER BY total_revenue DESC;
-- How many sales were made each day?
SELECT 
    DATE(SaleDate) AS Sale_Day, COUNT(*) AS Total_Sales
FROM
    sales
WHERE
    SaleDate IS NOT NULL
GROUP BY DATE(SaleDate)
ORDER BY Sale_Day;
-- Which date had the highest total sales?
SELECT 
    DATE(SaleDate) AS Sale_Day,
    COUNT(*) AS Total_Sales
FROM 
    sales
WHERE 
    SaleDate IS NOT NULL
GROUP BY 
    DATE(SaleDate)
ORDER BY 
    Sale_Day
    limit 1;
-- What's the total number of boxes sold per product category?
 SELECT 
    p.Category,
    SUM(s.Boxes) AS Total_Boxes_Sold
FROM 
    sales AS s
JOIN 
    products AS p USING (PID)
GROUP BY 
    p.Category
ORDER BY 
    Total_Boxes_Sold DESC;
   -- 🧍‍♂️ People & Teams
-- How many salespeople are on each team?
SELECT 
    Team,
    COUNT(Salesperson) AS Num_Salespeople
FROM 
    people
WHERE 
    Team IS NOT NULL AND Team != ''
GROUP BY 
    Team
ORDER BY 
    Num_Salespeople DESC;
    
-- List salespeople who don’t belong to any team.

SELECT 
    Team, Salesperson, SPID, Location
FROM
    people
WHERE
    Team IS NULL OR Team = '';
    
-- Which salesperson had the most unique products sold?
SELECT 
    pe.Salesperson,
    s.SPID,
    COUNT(DISTINCT s.PID) AS Unique_Products_Sold
FROM 
    sales s
JOIN 
    people pe ON s.SPID = pe.SPID
GROUP BY 
    s.SPID, pe.Salesperson
ORDER BY 
    Unique_Products_Sold DESC;
SELECT 
    pe.Salesperson,
    s.SPID,
    COUNT(DISTINCT s.PID) AS Unique_Products_Sold
FROM 
    sales s
JOIN 
    people pe ON s.SPID = pe.SPID
GROUP BY 
    s.SPID, pe.Salesperson
ORDER BY 
    Unique_Products_Sold DESC
    limit 1;
 -- Which salesperson has the highest average sale per transaction?
 SELECT 
    pe.Salesperson,
    s.SPID,
    AVG(s.Amount) AS Avg_Sale_Per_Transaction
FROM 
    sales s
JOIN 
    people pe ON s.SPID = pe.SPID
GROUP BY 
    s.SPID, pe.Salesperson
ORDER BY 
    Avg_Sale_Per_Transaction DESC
LIMIT 1;

-- What's the average revenue per team?
 SELECT 
p.Team, AVG(s.Amount) AS 'Average_Revenue_per_Team'
FROM
    sales AS s
        JOIN
    people AS p USING (SPID)
WHERE
    p.Team IS NOT NULL or p.Team != ' '
GROUP BY p.Team;
